Update HelloWorld.ino documentation links
arduino-libraries/LiquidCrystal pull request #66
Opened 2023-02-07 16:52 UTC by drf5n

Update documentation link per issue https://github.com/arduino-libraries/LiquidCrystal/issues/65

2023-02-07 16:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/arduino-libraries/LiquidCrystal?pullRequest=66) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/arduino-libraries/LiquidCrystal?pullRequest=66) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/arduino-libraries/LiquidCrystal?pullRequest=66) it.</sub>

2023-02-07 17:23 UTC, drf5n commented
I'm not sure how to edit more than one file per commit through Github's edit/fork/pr tool.

2023-02-07 21:20 UTC, per1234 requested changes

2023-02-07 21:20 UTC, per1234 commented on examples/setCursor/setCursor.ino
> + https://docs.arduino.cc/learn/electronics/lcd-displays#cursor-example
```suggestion
 https://docs.arduino.cc/learn/electronics/lcd-displays#cursor
```

Correct the anchor ID

2023-02-08 04:12 UTC, per1234 approved these changes
Thanks @drf5n!

2023-02-08 04:13 UTC, merged